routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('reset-config', function(){
  Artisan::call('config:cache');
  Artisan::call('view:clear');
});

Route::get('/', function(){
  return redirect(route('dashboard.index'));
});

Route::get('download', function(){
  return response()->file(public_path("uploads/ecofo.apk") ,[
      'Content-Type'=>'application/vnd.android.package-archive',
      'Content-Disposition'=> 'attachment; filename="ecofo.apk"',
  ]);
});

Route::get('login', 'LoginController@index')->name('login');
Route::post('login', 'LoginController@login')->name('login.login');
Route::get('logout', 'LoginController@logout')->name('logout.logout');

Route::group(['middleware'=>['auth']], function(){

  Route::prefix('dashboard')->group(function(){
    Route::get('', 'DashboardController@index')->name('dashboard.index');
    Route::get('axIndex', 'DashboardController@axIndex')->name('dashboard.axIndex');
  });

  Route::prefix('transaksi')->group(function(){
    Route::get('', 'TransaksiTiketController@index')->name('transaksi_tiket.index');
    Route::get('tambah', 'TransaksiTiketController@add')->name('transaksi_tiket.add');
    Route::post('', 'TransaksiTiketController@store')->name('transaksi_tiket.store');
    Route::post('delete/{id}', 'TransaksiTiketController@delete')->name('transaksi_tiket.delete');
  });
  
  Route::prefix('laporan')->group(function(){
    Route::get('realisasi', 'LaporanController@realisasi')->name('laporan.realisasi'); 
    Route::get('perolehan', 'LaporanController@perolehan')->name('laporan.perolehan'); 
    Route::get('berita-acara', 'LaporanController@beritaAcara')->name('laporan.berita_acara');     
  });
  
  Route::prefix('master-data')->group(function(){
    Route::prefix('kph')->group(function(){
      Route::get('', 'KphController@index')->name('kph.index');
      Route::get('ax', 'KphController@axIndex')->name('kph.axIndex');
      Route::post('', 'KphController@store')->name('kph.store');
      Route::post('update/{id}', 'KphController@update')->name('kph.update');
      Route::post('delete/{id}', 'KphController@delete')->name('kph.delete');    
    });
  
    Route::prefix('pengguna')->group(function(){
      Route::get('', 'UserController@index')->name('user.index');
      Route::get('tambah', 'UserController@add')->name('user.add');
      Route::get('edit/{id}', 'UserController@edit')->name('user.edit');
      Route::get('ax', 'UserController@axIndex')->name('user.axIndex');
      Route::post('', 'UserController@store')->name('user.store');
      Route::post('update/{id}', 'UserController@update')->name('user.update');
      Route::post('delete/{id}', 'UserController@delete')->name('user.delete');    
    });
  
    Route::prefix('jenis-tiket')->group(function(){
      Route::get('', 'JenisTiketController@index')->name('jenis_tiket.index');
      Route::post('', 'JenisTiketController@store')->name('jenis_tiket.store');
      Route::post('update/{id}', 'JenisTiketController@update')->name('jenis_tiket.update');
      Route::post('delete/{id}', 'JenisTiketController@delete')->name('jenis_tiket.delete');    
    });
  
    Route::prefix('lokasi')->group(function(){
      Route::get('', 'LokasiController@index')->name('lokasi.index');
      Route::get('edit/{id}', 'LokasiController@edit')->name('lokasi.edit');
      Route::get('ax', 'LokasiController@axIndex')->name('lokasi.axIndex');
      Route::get('detail/{id}', 'LokasiController@detail')->name('lokasi.detail');
      Route::post('', 'LokasiController@store')->name('lokasi.store');
      Route::post('update/{id}', 'LokasiController@update')->name('lokasi.update');
      Route::post('delete/{id}', 'LokasiController@delete')->name('lokasi.delete');    
    });
  
    Route::prefix('loket')->group(function(){
      Route::get('', 'LoketController@index')->name('loket.index');
      Route::get('detail/{id}', 'LoketController@detail')->name('loket.detail');
      Route::get('edit/{id}', 'LoketController@edit')->name('loket.edit');
      Route::get('ax', 'LoketController@axIndex')->name('loket.axIndex');
      Route::post('', 'LoketController@store')->name('loket.store');
      Route::post('update/{id}', 'LoketController@update')->name('loket.update');
      Route::post('delete/{id}', 'LoketController@delete')->name('loket.delete');    
    });
  
    Route::prefix('role')->group(function(){
      Route::get('', 'RoleController@index')->name('role.index');
      Route::get('tambah', 'RoleController@add')->name('role.add');
      Route::get('edit/{id}', 'RoleController@edit')->name('role.edit');
      Route::post('', 'RoleController@store')->name('role.store');
      Route::post('update/{id}', 'RoleController@update')->name('role.update');
      Route::post('delete/{id}', 'RoleController@delete')->name('role.delete');    
    });
  
    Route::prefix('tiket')->group(function(){
      Route::get('', 'TiketWisataController@index')->name('tiket.index');
      Route::get('ax', 'TiketWisataController@axIndex')->name('tiket.axIndex');
      Route::get('tambah', 'TiketWisataController@add')->name('tiket.add');
      Route::get('detail/{id}', 'TiketWisataController@detail')->name('tiket.detail');
      Route::get('edit/{id}', 'TiketWisataController@edit')->name('tiket.edit');
      Route::post('', 'TiketWisataController@store')->name('tiket.store');
      Route::post('update/{id}', 'TiketWisataController@update')->name('tiket.update');
      Route::post('delete/{id}', 'TiketWisataController@delete')->name('tiket.delete');    
    });
  
    Route::prefix('target-perolehan')->group(function(){
      Route::get('', 'TargetPerolehanController@index')->name('target_perolehan.index');
      Route::post('', 'TargetPerolehanController@store')->name('target_perolehan.store');
      Route::post('update/{id}', 'TargetPerolehanController@update')->name('target_perolehan.update');
      Route::post('delete/{id}', 'TargetPerolehanController@delete')->name('target_perolehan.delete');    
    });
  
    Route::prefix('biaya-operasional')->group(function(){
      Route::get('', 'BiayaOperasionalController@index')->name('biaya_operasional.index');
      Route::post('', 'BiayaOperasionalController@store')->name('biaya_operasional.store');
      Route::post('update/{id}', 'BiayaOperasionalController@update')->name('biaya_operasional.update');
      Route::post('delete/{id}', 'BiayaOperasionalController@delete')->name('biaya_operasional.delete');    
    });
  
    Route::prefix('mitra')->group(function(){
      Route::get('', 'MitraController@index')->name('mitra.index');
      Route::get('ax', 'MitraController@axIndex')->name('mitra.axIndex');
      Route::post('', 'MitraController@store')->name('mitra.store');
      Route::post('update/{id}', 'MitraController@update')->name('mitra.update');
      Route::post('delete/{id}', 'MitraController@delete')->name('mitra.delete');    
    });
  });
});

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Auth;

class User extends Authenticatable {

  use Notifiable;
  protected $fillable = [
    'name', 'email', 'password',
  ];
  
  protected $hidden = [
    'password', 'remember_token',
  ];

  protected static function boot(){
    parent::boot();

    static::addGlobalScope('orderByName', function(Builder $builder){
      $builder->orderBy('nama');
    });
  }

  public function getNamaAttribute($nama){
    return strtoupper($nama);
  }

  public function getFotoPathAttribute(){
    return $this->foto ? asset('uploads/users/'.$this->foto) : asset('placeholder.jpg');
  }

  public function getAuthLevelAttribute(){
    return Auth::check() ? Auth::user()->level->nama : null;
  }

  public function getKphListIdAttribute(){
    $auth = Auth::user();
    $kph = Kph::active();
    $level = strtolower($auth->level->nama);
    
    if($level == 'regional'){
      $kph = $kph->where('unit_kerja_id', $auth->kph->unit_kerja_id);
    }elseif($level == 'kph' || $level == 'loket'){
      $kph = $kph->where('id', $auth->kph_id);
    }

    return $kph->select('id')->get()->toArray();
  }

  public function hasPermission($routeName){
    return in_array($routeName, $this->permissions());
  }

  public function kph(){
    return $this->belongsTo('App\Kph');
  }

  public function level(){
    return $this->belongsTo('App\Level');
  }

  //ini salah
  public function loket(){
    return $this->hasOne('App\Loket')->where('is_active', true);
  }

  public function userLoket(){
    return $this->hasOne('App\UserLoket')->latest('id');
  }

  public function permissions(){
    $idRoles = $this->userRole()->select('role_id')->get()->toArray();
    $idPermissions = RolePermission::whereIn('role_id', $idRoles)->select('permission_id')->get()->toArray();
    $permissionsObj = Permission::whereIn('id', $idPermissions)->select('route')->get();
    $permissionsArr = array();
    foreach($permissionsObj as $o){
      array_push($permissionsArr, $o->route);
    }
    
    return $permissionsArr;
  }

  public function scopeActive($query){
    return $query->where('is_active', true);
  }  

  public function scopeInMyOrganization($query){
    return $query->whereIn('kph_id', Auth::user()->kph_list_id);
  }

  public function userRole(){
    return $this->hasMany('App\UserRole');
  }

}

resources/views/app.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Efoco System | Sistem eTicketing Wisata Perum Perhutani">
  <meta name="author" content="shafarizkyf">
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <!-- App Favicon -->
  <link rel="shortcut icon" href="{{ asset('template/assets/images/favicon.ico') }}">
  <!-- App title -->
  <title>Ecofo | @yield('title')</title>
  
  @yield('css-top')
  
  <!-- App CSS -->
  <link href="{{ asset('template/assets/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
  <link href="{{ asset('template/assets/css/core.css') }}" rel="stylesheet" type="text/css" />
  <link href="{{ asset('template/assets/css/components.css') }}" rel="stylesheet" type="text/css" />
  <link href="{{ asset('template/assets/css/icons.css') }}" rel="stylesheet" type="text/css" />
  <link href="{{ asset('template/assets/css/pages.css') }}" rel="stylesheet" type="text/css" />
  <link href="{{ asset('template/assets/css/menu.css') }}" rel="stylesheet" type="text/css" />
  <link href="{{ asset('template/assets/css/responsive.css') }}" rel="stylesheet" type="text/css" />

  @yield('css-bottom')

  <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->    
  <script src="{{ asset('template/assets/js/modernizr.min.js') }}"></script>
    
  </head>
  
  <body class="fixed-left">  
    <!-- Begin page -->
    <div id="wrapper">
      <!-- Top Bar Start -->
      <div class="topbar">
        <!-- LOGO -->
        <div class="topbar-left">
          <a href="index.html" class="logo"><span>Eco<span>fo</span></span><i class="zmdi zmdi-layers"></i></a>
        </div>
        <!-- Button mobile view to collapse sidebar menu -->
        <div class="navbar navbar-default" role="navigation">
          <div class="container">
            <!-- Page title -->
            <ul class="nav navbar-nav navbar-left">
              <li>
                <button class="button-menu-mobile open-left">
                  <i class="zmdi zmdi-menu"></i>
                </button>
              </li>
              <li>
                <h4 class="page-title">@yield('title-page')</h4>
              </li>
            </ul>
            
          </div><!-- end container -->
        </div><!-- end navbar -->
      </div>
      <!-- Top Bar End -->
      
      <!-- ========== Left Sidebar Start ========== -->
      <div class="left side-menu">
        <div class="sidebar-inner slimscrollleft">
          <!-- User -->
          <div class="user-box">
            <div class="user-img">
              <img src="{{ Auth::user()->foto_path }}" alt="user-img" title="{{ Auth::user()->nama }}" class="img-circle img-thumbnail img-responsive">
            </div>
            <h5><a href="#">{{ Auth::user()->nama }}</a> </h5>
            <ul class="list-inline">
              <li>
                <a href="{{ route('logout.logout') }}" class="text-custom">
                  <i class="zmdi zmdi-power"></i>
                </a>
              </li>              
            </ul>
          </div>
          <!-- End User -->
          <!--- Sidebar -->
          <div id="sidebar-menu">
            <ul>
              <li class="text-muted menu-title">Main Menu</li>
              
              @if(Auth::user()->hasPermission('dashboard.index'))
              <li>
                <a href="{{ route('dashboard.index') }}" class="waves-effect"><i class="ti ti-dashboard"></i> <span>Dashboard</span></a>
              </li>
              @endif

              @if(Auth::user()->hasPermission('transaksi_tiket.index'))
              <li>
                <a href="{{ route('transaksi_tiket.index') }}" class="waves-effect"><i class="ti ti-receipt"></i> <span>Transaksi</span></a>
              </li>
              @endif
              
              @if(Auth::user()->hasPermission('laporan.realisasi') || Auth::user()->hasPermission('laporan.pendapatan'))
              <li class="has_sub">
                <a href="javascript:void(0);" class="waves-effect"><i class="ti ti-agenda"></i><span> Laporan</span> <span class="menu-arrow"></span></a>
                <ul class="list-unstyled">
                  @if(Auth::user()->hasPermission('laporan.realisasi'))    
                  <li><a href="{{ route('laporan.realisasi') }}">Realisasi</a></li>
                  @endif
                  
                  @if(Auth::user()->hasPermission('laporan.perolehan'))    
                  <li><a href="{{ route('laporan.perolehan') }}">Perolehan</a></li>
                  @endif
                </ul>
              </li>
              @endif

              @if(
                Auth::user()->hasPermission('tiket.index') || 
                Auth::user()->hasPermission('loket.index') ||
                Auth::user()->hasPermission('lokasi.index') ||
                Auth::user()->hasPermission('jenis_tiket.index'))
              <li class="has_sub">
                <a href="javascript:void(0);" class="waves-effect"><i class="ti ti-ticket"></i><span> Tiket Wisata</span> <span class="menu-arrow"></span></a>
                <ul class="list-unstyled">
                  
                  @if(Auth::user()->hasPermission('tiket.index'))                  
                  <li><a href="{{ route('tiket.index') }}">Tiket</a></li>
                  @endif
                  
                  @if(Auth::user()->hasPermission('loket.index'))                  
                  <li><a href="{{ route('loket.index') }}">Loket</a></li>
                  @endif
                  
                  @if(Auth::user()->hasPermission('lokasi.index'))                  
                  <li><a href="{{ route('lokasi.index') }}">Lokasi</a></li>
                  @endif

                  @if(Auth::user()->hasPermission('jenis_tiket.index'))                  
                  <li><a href="{{ route('jenis_tiket.index') }}">Jenis Tiket</a></li>
                  @endif
                </ul>
              </li>
              @endif
              
              @if(
                Auth::user()->hasPermission('target_perolehan.index') || 
                Auth::user()->hasPermission('biaya_operasional.index') ||
                Auth::user()->hasPermission('mitra.index') ||
                Auth::user()->hasPermission('kph.index'))
              <li class="has_sub">
                <a href="javascript:void(0);" class="waves-effect"><i class="ti ti-book"></i><span> Master Data </span> <span class="menu-arrow"></span></a>
                <ul class="list-unstyled">

                  @if(Auth::user()->hasPermission('target_perolehan.index'))
                  <li><a href="{{ route('target_perolehan.index') }}">Target Perolehan</a></li>
                  @endif

                  @if(Auth::user()->hasPermission('biaya_operasional.index'))
                  <li><a href="{{ route('biaya_operasional.index') }}">Komponen Biaya</a></li>
                  @endif

                  @if(Auth::user()->hasPermission('mitra.index'))
                  <li><a href="{{ route('mitra.index') }}">Mitra</a></li>
                  @endif

                  @if(Auth::user()->hasPermission('kph.index'))
                  <li><a href="{{ route('kph.index') }}">KPH</a></li>
                  @endif

                </ul>
              </li>
              @endif

              @if(Auth::user()->hasPermission('user.index') || Auth::user()->hasPermission('role.index'))
              <li class="has_sub">
                <a href="javascript:void(0);" class="waves-effect"><i class="ti ti-user"></i><span> Managemen Pengguna </span> <span class="menu-arrow"></span></a>
                <ul class="list-unstyled">

                  @if(Auth::user()->hasPermission('user.index'))
                  <li><a href="{{ route('user.index') }}">Pengguna</a></li>
                  @endif

                  @if(Auth::user()->hasPermission('role.index'))
                  <li><a href="{{ route('role.index') }}">Role</a></li>
                  @endif

                </ul>
              </li>
              @endif


            </ul>
            <div class="clearfix"></div>
          </div>
          <!-- Sidebar -->
          <div class="clearfix"></div>              
        </div>            
      </div>
      <!-- Left Sidebar End -->
                                    
      <!-- ============================================================== -->
      <!-- Start right Content here -->
      <!-- ============================================================== -->
      <div class="content-page">
        <!-- Start content -->
        <div class="content">
          <div class="container">

            @if(Session::has('success'))
            <div class="row">
              <div class="col-sm-12">
                <div class="card m-b-0 bg-success text-xs-center">
                  <div class="card-body">
                    <blockquote class="card-bodyquote">
                      <h5 class="text-white m-0"><strong><i class="fa fa-check"></i> Oke!</strong> {{ Session::get('success') }}</h5>
                    </blockquote>
                  </div>                  
                </div>
              </div>
            </div>
            @endif

            @if(Session::has('warning'))
            <div class="row">
              <div class="col-sm-12">
                <div class="card m-b-0 bg-warning text-xs-center">
                  <div class="card-body">
                    <blockquote class="card-bodyquote">
                      <h5 class="text-white m-0"><strong><i class="fa fa-info"></i> Ups!</strong> {{ Session::get('warning') }}</h5>
                    </blockquote>
                  </div>                  
                </div>
              </div>
            </div>
            @endif

            @if(Session::has('danger'))
            <div class="row">
              <div class="col-sm-12">
                <div class="card m-b-0 bg-danger text-xs-center">
                  <div class="card-body">
                    <blockquote class="card-bodyquote">
                      <h5 class="text-white m-0"><strong><i class="fa fa-info"></i> Ups!</strong> {{ Session::get('danger') }}</h5>
                    </blockquote>
                  </div>                  
                </div>
              </div>
            </div>
            @endif

            @yield('content')

          </div> <!-- container -->
        </div> <!-- content -->
        

        <footer class="footer">
          © {{ date('Y') }} Perum Perhutani
        </footer>

        @yield('modal')
        
      </div>
      <!-- End content-page -->
      
      <!-- ============================================================== -->
      <!-- End Right content here -->
      <!-- ============================================================== -->
      <!-- Right Sidebar -->
      <div class="side-bar right-bar">
        <a href="javascript:void(0);" class="right-bar-toggle">
          <i class="zmdi zmdi-close-circle-o"></i>
        </a>
      </div>
      <!-- /Right-bar -->      
    </div>

    <!-- END wrapper -->
    <script>var resizefunc = [];</script>    
    <!-- jQuery  -->
    <script src="{{ asset('template/assets/js/jquery.min.js') }}"></script>
    <script src="{{ asset('template/assets/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('template/assets/js/detect.js') }}"></script>
    <script src="{{ asset('template/assets/js/fastclick.js') }}"></script>
    <script src="{{ asset('template/assets/js/jquery.slimscroll.js') }}"></script>
    <script src="{{ asset('template/assets/js/jquery.blockUI.js') }}"></script>
    <script src="{{ asset('template/assets/js/waves.js') }}"></script>
    <script src="{{ asset('template/assets/js/jquery.nicescroll.js') }}"></script>
    <script src="{{ asset('template/assets/js/jquery.scrollTo.min.js') }}"></script>

    @yield('js-top')
    
    <!-- App js -->
    <script src="{{ asset('template/assets/js/jquery.core.js') }}"></script>
    <script src="{{ asset('template/assets/js/jquery.app.js') }}"></script> 
    
    @yield('js-bottom')
    
</body>
</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection