routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('reset-config', function(){
  Artisan::call('config:cache');
  Artisan::call('view:clear');
});

Route::get('/', function(){
  return redirect(route('dashboard.index'));
});

Route::get('download', function(){
  return response()->file(public_path("uploads/ecofo.apk") ,[
      'Content-Type'=>'application/vnd.android.package-archive',
      'Content-Disposition'=> 'attachment; filename="ecofo.apk"',
  ]);
});

Route::get('login', 'LoginController@index')->name('login');
Route::post('login', 'LoginController@login')->name('login.login');
Route::get('logout', 'LoginController@logout')->name('logout.logout');

Route::group(['middleware'=>['auth']], function(){

  Route::prefix('dashboard')->group(function(){
    Route::get('', 'DashboardController@index')->name('dashboard.index');
    Route::get('axIndex', 'DashboardController@axIndex')->name('dashboard.axIndex');
  });

  Route::prefix('transaksi')->group(function(){
    Route::get('', 'TransaksiTiketController@index')->name('transaksi_tiket.index');
    Route::get('tambah', 'TransaksiTiketController@add')->name('transaksi_tiket.add');
    Route::post('', 'TransaksiTiketController@store')->name('transaksi_tiket.store');
    Route::post('delete/{id}', 'TransaksiTiketController@delete')->name('transaksi_tiket.delete');
  });
  
  Route::prefix('laporan')->group(function(){
    Route::get('realisasi', 'LaporanController@realisasi')->name('laporan.realisasi'); 
    Route::get('perolehan', 'LaporanController@perolehan')->name('laporan.perolehan'); 
    Route::get('berita-acara', 'LaporanController@beritaAcara')->name('laporan.berita_acara');     
  });
  
  Route::prefix('master-data')->group(function(){
    Route::prefix('kph')->group(function(){
      Route::get('', 'KphController@index')->name('kph.index');
      Route::get('ax', 'KphController@axIndex')->name('kph.axIndex');
      Route::post('', 'KphController@store')->name('kph.store');
      Route::post('update/{id}', 'KphController@update')->name('kph.update');
      Route::post('delete/{id}', 'KphController@delete')->name('kph.delete');    
    });
  
    Route::prefix('pengguna')->group(function(){
      Route::get('', 'UserController@index')->name('user.index');
      Route::get('tambah', 'UserController@add')->name('user.add');
      Route::get('edit/{id}', 'UserController@edit')->name('user.edit');
      Route::get('ax', 'UserController@axIndex')->name('user.axIndex');
      Route::post('', 'UserController@store')->name('user.store');
      Route::post('update/{id}', 'UserController@update')->name('user.update');
      Route::post('delete/{id}', 'UserController@delete')->name('user.delete');    
    });
  
    Route::prefix('jenis-tiket')->group(function(){
      Route::get('', 'JenisTiketController@index')->name('jenis_tiket.index');
      Route::post('', 'JenisTiketController@store')->name('jenis_tiket.store');
      Route::post('update/{id}', 'JenisTiketController@update')->name('jenis_tiket.update');
      Route::post('delete/{id}', 'JenisTiketController@delete')->name('jenis_tiket.delete');    
    });
  
    Route::prefix('lokasi')->group(function(){
      Route::get('', 'LokasiController@index')->name('lokasi.index');
      Route::get('edit/{id}', 'LokasiController@edit')->name('lokasi.edit');
      Route::get('ax', 'LokasiController@axIndex')->name('lokasi.axIndex');
      Route::get('detail/{id}', 'LokasiController@detail')->name('lokasi.detail');
      Route::post('', 'LokasiController@store')->name('lokasi.store');
      Route::post('update/{id}', 'LokasiController@update')->name('lokasi.update');
      Route::post('delete/{id}', 'LokasiController@delete')->name('lokasi.delete');    
    });
  
    Route::prefix('loket')->group(function(){
      Route::get('', 'LoketController@index')->name('loket.index');
      Route::get('detail/{id}', 'LoketController@detail')->name('loket.detail');
      Route::get('edit/{id}', 'LoketController@edit')->name('loket.edit');
      Route::get('ax', 'LoketController@axIndex')->name('loket.axIndex');
      Route::post('', 'LoketController@store')->name('loket.store');
      Route::post('update/{id}', 'LoketController@update')->name('loket.update');
      Route::post('delete/{id}', 'LoketController@delete')->name('loket.delete');    
    });
  
    Route::prefix('role')->group(function(){
      Route::get('', 'RoleController@index')->name('role.index');
      Route::get('tambah', 'RoleController@add')->name('role.add');
      Route::get('edit/{id}', 'RoleController@edit')->name('role.edit');
      Route::post('', 'RoleController@store')->name('role.store');
      Route::post('update/{id}', 'RoleController@update')->name('role.update');
      Route::post('delete/{id}', 'RoleController@delete')->name('role.delete');    
    });
  
    Route::prefix('tiket')->group(function(){
      Route::get('', 'TiketWisataController@index')->name('tiket.index');
      Route::get('ax', 'TiketWisataController@axIndex')->name('tiket.axIndex');
      Route::get('tambah', 'TiketWisataController@add')->name('tiket.add');
      Route::get('detail/{id}', 'TiketWisataController@detail')->name('tiket.detail');
      Route::get('edit/{id}', 'TiketWisataController@edit')->name('tiket.edit');
      Route::post('', 'TiketWisataController@store')->name('tiket.store');
      Route::post('update/{id}', 'TiketWisataController@update')->name('tiket.update');
      Route::post('delete/{id}', 'TiketWisataController@delete')->name('tiket.delete');    
    });
  
    Route::prefix('target-perolehan')->group(function(){
      Route::get('', 'TargetPerolehanController@index')->name('target_perolehan.index');
      Route::post('', 'TargetPerolehanController@store')->name('target_perolehan.store');
      Route::post('update/{id}', 'TargetPerolehanController@update')->name('target_perolehan.update');
      Route::post('delete/{id}', 'TargetPerolehanController@delete')->name('target_perolehan.delete');    
    });
  
    Route::prefix('biaya-operasional')->group(function(){
      Route::get('', 'BiayaOperasionalController@index')->name('biaya_operasional.index');
      Route::post('', 'BiayaOperasionalController@store')->name('biaya_operasional.store');
      Route::post('update/{id}', 'BiayaOperasionalController@update')->name('biaya_operasional.update');
      Route::post('delete/{id}', 'BiayaOperasionalController@delete')->name('biaya_operasional.delete');    
    });
  
    Route::prefix('mitra')->group(function(){
      Route::get('', 'MitraController@index')->name('mitra.index');
      Route::get('ax', 'MitraController@axIndex')->name('mitra.axIndex');
      Route::post('', 'MitraController@store')->name('mitra.store');
      Route::post('update/{id}', 'MitraController@update')->name('mitra.update');
      Route::post('delete/{id}', 'MitraController@delete')->name('mitra.delete');    
    });
  });
});

app/TiketWisata.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class TiketWisata extends Model{

  public function bagiHasil(){
    return $this->hasMany('App\BagiHasil');
  }

  public function getCreatedAtAttribute($date){
    return Carbon::parse($date);
  }

  public function getJenisWaktuAttribute($jenis){
    return $jenis == 'all' ? 'SEMUA HARI' : strtoupper($jenis);
  }

  public function getHargaFormatAttribute(){
    return number_format($this->harga);
  }

  public function getActiveAttribute($date){
    return $this->is_active ? 'Aktif' : 'Dimatikan';
  }

  public function komponenHarga(){
    return $this->hasMany('App\KomponenHarga');
  }

  public function lokasi(){
    return $this->belongsTo('App\Lokasi');
  }

  public function loket(){
    return $this->belongsTo('App\Loket');
  }

  public function jenisTiket(){
    return $this->belongsTo('App\JenisTiket');
  }

  public function scopeActive($query){
    return $query->where('is_active', true);
  }

  public function scopeInMyOrganization($query){
    return $query->whereHas('lokasi', function($q){
      $q->whereIn('kph_id', Auth::user()->kph_list_id);
    });
  }

  public function transaksi(){
    return $this->hasMany('App\TransaksiTiket');
  }

}

app/TransaksiTiket.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;

class TransaksiTiket extends Model{
    
  public function bagiHasil(){
    return $this->hasMany('App\BagiHasil', 'tiket_wisata_id', 'tiket_wisata_id');
  }

  public function createdBy(){
    return $this->belongsTo('App\User', 'created_by');
  }

  public function tiketWisata(){
    return $this->belongsTo('App\TiketWisata');
  }
  
  public function getCreatedAtAttribute($date){
    return Carbon::parse($date)->addHours(7);
  }
  
  public function scopeDate($query, $date){
    return $query->startDate($date)->endDate($date);
  }

  public function scopeEndDate($query, $date){
    return $query->whereDate('created_at', '<=', $date);
  }

  public function scopeInMyOrganization($query){
    $auth =  Auth::user();

    if($auth->level->nama == 'Loket'){
      return $query->where('created_by', $auth->id);
    }else{
      return $query->whereHas('tiketWisata.lokasi', function($q) use ($auth){
        $q->whereIn('kph_id', $auth->kph_list_id);
      });
    }
  }

  public function scopeJenisTiket($query, $idJenisTiket){
    return $query->whereHas('tiketWisata', function($q) use ($idJenisTiket){
      $q->where('jenis_tiket_id', $idJenisTiket);
    });
  }

  public function scopeKph($query, $idKph){
    return $query->whereHas('tiketWisata.lokasi', function($q) use ($idKph){
      $q->where('kph_id', $idKph);
    });    
  }

  public function scopeLokasi($query, $idLokasi){
    return $query->whereHas('tiketWisata', function($q) use ($idLokasi){
      $q->where('lokasi_id', $idLokasi);
    });
  }

  public function scopeStartDate($query, $date){
    return $query->whereDate('created_at', '>=', $date);
  }

  public function scopeByDate($query){
    return $query->groupBy(DB::raw('Date(created_at)'));
  }

  public function scopeTransaksi($query){
    return $query->byDate()->select(DB::raw('*, count(id) as total, min(nomor_karcis) as min, max(nomor_karcis) as max'));
  }

}

app/Http/Controllers/TransaksiTiketController.php
<?php

namespace App\Http\Controllers;

use App\MyClass\Common;

use App\JenisTiket;
use App\Kph;
use App\Lokasi;
use App\Loket;
use App\TiketWisata;
use App\TransaksiTiket;
use App\UnitKerja;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;

class TransaksiTiketController extends Controller{
  
  public function index(Request $request){
    Common::hasPermission();
    
    $transaksi = TransaksiTiket::inMyOrganization();

    if(!isset($request->date) && (!isset($request->tanggal_dari) || !isset($request->tanggal_sampai))){
      $transaksi = $transaksi->whereDate('created_at', date('Y-m-d'));
    }

    if(isset($request->date)){
      $transaksi = $transaksi->date($request->date);
    }
    
    if(isset($request->tanggal_dari)){
      $transaksi = $transaksi->startDate($request->tanggal_dari);
    }

    if(isset($request->tanggal_sampai)){
      $transaksi = $transaksi->endDate($request->tanggal_sampai);
    }

    if(isset($request->lokasi)){
      $transaksi = $transaksi->lokasi($request->lokasi);
    }

    if(isset($request->jenis_tiket)){
      $transaksi = $transaksi->jenisTiket($request->jenis_tiket);
    }

    $kph = Kph::active()->inMyOrganization()->select('id')->get()->toArray();
    $lokasi = Lokasi::active()->inMyOrganization()->get();
    $jenisTiket = JenisTiket::active()->get();

    $transaksi = $transaksi->latest('id')->get();
    return view('transaksi_tiket.index', compact('transaksi', 'lokasi', 'jenisTiket'));
  }

  public function add(){
    Common::hasPermission();

    $unitKerja = UnitKerja::active()->inMyOrganization()->get();
    return view('transaksi_tiket.add', compact('unitKerja'));
  }

  public function store(Request $request){
    Common::hasPermission();
    
    DB::transaction(function() use ($request){
      foreach($request->data as $o){
        $tiket = TiketWisata::where('lokasi_id', $o['lokasi'])
        ->where('jenis_tiket_id', $o['jenis_tiket'])
        ->where('loket_id', $o['loket'])
        ->first();

        for($i=0; $i<$o['jumlah']; $i++){
          $transaksi = new TransaksiTiket();
          $transaksi->nomor_karcis = $this->generateKodeKarcis($tiket);
          $transaksi->negara_pengunjung = $tiket->jenisTiket->jenis;
          $transaksi->harga = $tiket->harga;
          $transaksi->tiketWisata()->associate($tiket);
          $transaksi->createdBy()->associate(Auth::user());
          $transaksi->save();
        }
      }
    });

    return redirect()->back()->with('success', 'Berhasil menambah data');
  }
  

  public function apiStore(Request $request){

    $response = ['success'=>false, 'msg'=>'Internal server error'];
    DB::transaction(function() use ($request, &$response){

      $user = User::find($request->id_user);
      $tiket = TiketWisata::find($request->id_tiket);
      
      for($i=0; $i<$request->jumlah; $i++){
        $transaksi = new TransaksiTiket();
        $transaksi->nomor_karcis = $this->generateKodeKarcis($tiket);
        $transaksi->negara_pengunjung = $tiket->jenisTiket->jenis;
        $transaksi->harga = $tiket->harga;

        if($request->created_at){
          $transaksi->created_at = $request->created_at;
        }

        $transaksi->tiketWisata()->associate($tiket);
        $transaksi->createdBy()->associate($user);
        $transaksi->save();
      }

      $response = ['success'=>true, 'msg'=>'Transaksi berhasil'];
    });

    return $response;
  }

  public function apiGetTransaction(Request $request){    
    $transaksi = TransaksiTiket::where('created_at', $request->date)
    ->where('created_by', $request->id_user)
    ->count();

    return ['total'=>$transaksi];
  }

  public function apiDeleteTransaction(Request $request){

    $response = ['success'=>false, 'msg'=>'Internal server error'];
    DB::transaction(function() use ($request, &$response){
      $transaksi = TransaksiTiket::where('created_at', $request->date)
      ->where('created_by', $request->id_user)
      ->delete();  
      $response = ['success'=>true, 'msg'=>'Data berhasil dihapus'];
    });

    return $response;
  }

  public function generateKodeKarcis($tiket){
    $nomor = '1';
    $latestTransaksi = TransaksiTiket::where('tiket_wisata_id', $tiket->id)->get()->last();

    if($latestTransaksi){
      $nomor = substr($latestTransaksi->nomor_karcis, -5, 5);
      $nomor = $nomor + 1;
    }

    $nomor = sprintf('%05d', $nomor);
    $lokasi = Lokasi::find($tiket->lokasi_id);
    return $lokasi->kode . '-' . date('dmy') . '-' . $nomor;
  }

  public function delete($id){
    $response = ['success'=>false, 'msg'=>'Internal server error'];
    DB::transaction(function() use ($id, &$response){
      TransaksiTiket::find($id)->delete();
      $response = ['success'=>true, 'msg'=>'Data berhasil dihapus'];
    });

    return $response;
  }

}

resources/views/transaksi_tiket/index.blade.php
@extends('app')

@section('title')
Transaksi Tiket
@endsection

@section('title-page')
Transaksi Tiket
@endsection

@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="card-box">
      <h4 class="header-title m-t-0 m-l-10">Filter Data</h4>
      <form action="">
        <div class="row">
          <div class="col-md-12">

            <div class="col-sm-3">
              <select name="lokasi" class="form-control select2">
                <option value="">Pilih Lokasi</option>
                @foreach($lokasi as $o)
                <option value="{{ $o->id }}">{{ $o->nama }}</option>
                @endforeach
              </select>
            </div>

            <div class="col-sm-3">
              <select name="jenis_tiket" class="form-control select2">
                <option value="">Pilih Jenis Tiket</option>
                @foreach($jenisTiket as $o)
                <option value="{{ $o->id }}">{{ $o->nama }}</option>
                @endforeach
              </select>
            </div>

            <div class="col-sm-4">
              <div class="input-daterange input-group" id="date-range">
                <input type="text" class="form-control" name="tanggal_dari" placeholder="Tanggal dari" />
                <span class="input-group-addon bg-primary b-0 text-white">to</span>
                <input type="text" class="form-control" name="tanggal_sampai" placeholder="Tanggal Sampai" />
              </div>
            </div>

            <div class="col-sm-2">
              <button class="btn btn-primary">Filter</button>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <div class="card-box table-responsive">
      
      @if(Auth::user()->hasPermission('transaksi_tiket.store'))
      <a href="{{ route('transaksi_tiket.add') }}" class="btn btn-success pull-right"><i class="ti ti-plus"></i> Transaksi</a>
      @endif

      <h4 class="header-title m-t-0 m-b-30">Data Transaski Tiket Hari Ini</h4>
      <table id="datatable-buttons" class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>#</th>
            <th>Tanggal</th>
            <th>Lokasi</th>
            <th>Jenis</th>
            <th>Loket</th>
            <th>Nomor Tiket</th>
            <th>Harga</th>
            <th>Petugas</th>
            @if(Auth::user()->hasPermission('transaksi_tiket.delete'))
            <th></th>
            @endif
          </tr>
        </thead>
        <tbody>
          @php $no=1 @endphp
          @foreach($transaksi as $o)
          <tr>
            <td>{{ $no++ }}</td>
            <td>{{ $o->created_at->format('d-m-Y H:i') }}</td>
            <td>{{ $o->tiketWisata->lokasi->nama }}</td>
            <td>{{ $o->tiketWisata->jenisTiket->nama }}</td>
            <td>{{ $o->tiketWisata->loket->nama }}</td>
            <td>{{ $o->nomor_karcis }}</td>
            <td>{{ $o->tiketWisata->harga_format }}</td>
            <td>{{ $o->createdBy->nama }}</td>
            @if(Auth::user()->hasPermission('transaksi_tiket.delete'))
            <td>
              <a type="button" class="btn btn-danger waves-effect waves-light btn-sm btn-delete m-b-5" data-route="{{ route('transaksi_tiket.delete', $o->id) }}"><i class="ti ti-trash"></i> Delete</a>
            </td>
            @endif
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div><!-- end col -->
</div>
@endsection

@section('css-top')
<!-- DataTables -->
<link href="{{ asset('template/assets/plugins/datatables/jquery.dataTables.min.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('template/assets/plugins/datatables/buttons.bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('template/assets/plugins/datatables/fixedHeader.bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('template/assets/plugins/datatables/responsive.bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('template/assets/plugins/datatables/scroller.bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
<!-- Datatable init js -->
<script src="{{ asset('template/assets/pages/datatables.init.js') }}"></script>
<!-- datepicker -->
<link href="{{ asset('template/assets/plugins/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}" rel="stylesheet">
<link href="{{ asset('template/assets/plugins/bootstrap-daterangepicker/daterangepicker.css') }}" rel="stylesheet">
<!-- select2 -->
<link href="{{ asset('template/assets/plugins/select2/dist/css/select2.css') }}" rel="stylesheet" type="text/css">
<link href="{{ asset('template/assets/plugins/select2/dist/css/select2-bootstrap.css') }}" rel="stylesheet" type="text/css">
  <!-- Sweet Alert css -->
  <link href="{{ asset('template/assets/plugins/bootstrap-sweetalert/sweet-alert.css') }}" rel="stylesheet" type="text/css" />
  <!-- Custom box css -->
  <link href="{{ asset('template/assets/plugins/custombox/dist/custombox.min.css') }}" rel="stylesheet">
@endsection

@section('js-top')
  <!-- Datatables-->
  <script src="{{ asset('template/assets/plugins/datatables/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('template/assets/plugins/datatables/dataTables.bootstrap.js') }}"></script>
  <script src="{{ asset('template/assets/plugins/datatables/dataTables.buttons.min.js') }}"></script>
  <script src="{{ asset('template/assets/plugins/datatables/buttons.bootstrap.min.js') }}"></script>
  <script src="{{ asset('template/assets/plugins/datatables/jszip.min.js') }}"></script>
  <script src="{{ asset('template/assets/plugins/datatables/pdfmake.min.js') }}"></script>
  <script src="{{ asset('template/assets/plugins/datatables/vfs_fonts.js') }}"></script>
  <script src="{{ asset('template/assets/plugins/datatables/buttons.html5.min.js') }}"></script>
  <script src="{{ asset('template/assets/plugins/datatables/buttons.print.min.js') }}"></script>
  <script src="{{ asset('template/assets/plugins/datatables/dataTables.fixedHeader.min.js') }}"></script>
  <script src="{{ asset('template/assets/plugins/datatables/dataTables.keyTable.min.js') }}"></script>
  <script src="{{ asset('template/assets/plugins/datatables/dataTables.responsive.min.js') }}"></script>
  <script src="{{ asset('template/assets/plugins/datatables/responsive.bootstrap.min.js') }}"></script>
  <script src="{{ asset('template/assets/plugins/datatables/dataTables.scroller.min.js') }}"></script>
  <!-- Datatable init js -->
  <script src="{{ asset('template/assets/pages/datatables.init.js') }}"></script>
  <!-- Datepicker -->
  <script src="{{ asset('template/assets/plugins/moment/moment.js') }}"></script>
  <script src="{{ asset('template/assets/plugins/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}"></script>
  <script src="{{ asset('template/assets/plugins/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
  <!-- select2 -->
  <script src="{{ asset('template/assets/plugins/select2/dist/js/select2.min.js') }}"></script>
  <!-- Sweet Alert js -->
  <script src="{{ asset('template/assets/plugins/bootstrap-sweetalert/sweet-alert.min.js') }}"></script>
@endsection

@section('js-bottom')
<script type="text/javascript">
  $(document).ready(function () {
    $('.select2').select2();
    jQuery('#date-range').datepicker({
      format: 'yyyy-mm-dd',
      toggleActive: true
    });
    TableManageButtons.init();
    
    $('body').delegate('.btn-delete', 'click', function(){
      var route = $(this).data('route');
      var _token = $('meta[name=csrf-token]').attr('content');

      swal({
        title: "Apakah benar data akan dihapus?",
        type: "warning",
        showCancelButton: true,
        confirmButtonColor: "#DD6B55",
        confirmButtonText: "Ya",
        cancelButtonText: "Tidak",
        closeOnConfirm: false,
        closeOnCancel: false
      },function (isConfirm) {
        if (isConfirm) {
          $.post(route, {_token}).done(function(data){
            if(data.success){
              swal({title: "Dihapus", text: "Data berhasil dihapus!", type: "success"}, function(){
                location.reload();
              });
            }else{
              swal("Error", data.msg, "error");
            }
          }).fail(function(error){
            console.log(error);
          });
        }else{
          swal("Dibatalkan", "Data tidak dihapus", "error");
        }//if confirm
      });//swall
    });//ondelete
  });
</script>
@endsection