routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('reset-config', function(){
  Artisan::call('config:cache');
  Artisan::call('view:clear');
});

Route::get('/', function(){
  return redirect(route('dashboard.index'));
});

Route::get('download', function(){
  return response()->file(public_path("uploads/ecofo.apk") ,[
      'Content-Type'=>'application/vnd.android.package-archive',
      'Content-Disposition'=> 'attachment; filename="ecofo.apk"',
  ]);
});

Route::get('login', 'LoginController@index')->name('login');
Route::post('login', 'LoginController@login')->name('login.login');
Route::get('logout', 'LoginController@logout')->name('logout.logout');

Route::group(['middleware'=>['auth']], function(){

  Route::prefix('dashboard')->group(function(){
    Route::get('', 'DashboardController@index')->name('dashboard.index');
    Route::get('axIndex', 'DashboardController@axIndex')->name('dashboard.axIndex');
  });

  Route::prefix('transaksi')->group(function(){
    Route::get('', 'TransaksiTiketController@index')->name('transaksi_tiket.index');
    Route::get('tambah', 'TransaksiTiketController@add')->name('transaksi_tiket.add');
    Route::post('', 'TransaksiTiketController@store')->name('transaksi_tiket.store');
    Route::post('delete/{id}', 'TransaksiTiketController@delete')->name('transaksi_tiket.delete');
  });
  
  Route::prefix('laporan')->group(function(){
    Route::get('realisasi', 'LaporanController@realisasi')->name('laporan.realisasi'); 
    Route::get('perolehan', 'LaporanController@perolehan')->name('laporan.perolehan'); 
    Route::get('berita-acara', 'LaporanController@beritaAcara')->name('laporan.berita_acara');     
  });
  
  Route::prefix('master-data')->group(function(){
    Route::prefix('kph')->group(function(){
      Route::get('', 'KphController@index')->name('kph.index');
      Route::get('ax', 'KphController@axIndex')->name('kph.axIndex');
      Route::post('', 'KphController@store')->name('kph.store');
      Route::post('update/{id}', 'KphController@update')->name('kph.update');
      Route::post('delete/{id}', 'KphController@delete')->name('kph.delete');    
    });
  
    Route::prefix('pengguna')->group(function(){
      Route::get('', 'UserController@index')->name('user.index');
      Route::get('tambah', 'UserController@add')->name('user.add');
      Route::get('edit/{id}', 'UserController@edit')->name('user.edit');
      Route::get('ax', 'UserController@axIndex')->name('user.axIndex');
      Route::post('', 'UserController@store')->name('user.store');
      Route::post('update/{id}', 'UserController@update')->name('user.update');
      Route::post('delete/{id}', 'UserController@delete')->name('user.delete');    
    });
  
    Route::prefix('jenis-tiket')->group(function(){
      Route::get('', 'JenisTiketController@index')->name('jenis_tiket.index');
      Route::post('', 'JenisTiketController@store')->name('jenis_tiket.store');
      Route::post('update/{id}', 'JenisTiketController@update')->name('jenis_tiket.update');
      Route::post('delete/{id}', 'JenisTiketController@delete')->name('jenis_tiket.delete');    
    });
  
    Route::prefix('lokasi')->group(function(){
      Route::get('', 'LokasiController@index')->name('lokasi.index');
      Route::get('edit/{id}', 'LokasiController@edit')->name('lokasi.edit');
      Route::get('ax', 'LokasiController@axIndex')->name('lokasi.axIndex');
      Route::get('detail/{id}', 'LokasiController@detail')->name('lokasi.detail');
      Route::post('', 'LokasiController@store')->name('lokasi.store');
      Route::post('update/{id}', 'LokasiController@update')->name('lokasi.update');
      Route::post('delete/{id}', 'LokasiController@delete')->name('lokasi.delete');    
    });
  
    Route::prefix('loket')->group(function(){
      Route::get('', 'LoketController@index')->name('loket.index');
      Route::get('detail/{id}', 'LoketController@detail')->name('loket.detail');
      Route::get('edit/{id}', 'LoketController@edit')->name('loket.edit');
      Route::get('ax', 'LoketController@axIndex')->name('loket.axIndex');
      Route::post('', 'LoketController@store')->name('loket.store');
      Route::post('update/{id}', 'LoketController@update')->name('loket.update');
      Route::post('delete/{id}', 'LoketController@delete')->name('loket.delete');    
    });
  
    Route::prefix('role')->group(function(){
      Route::get('', 'RoleController@index')->name('role.index');
      Route::get('tambah', 'RoleController@add')->name('role.add');
      Route::get('edit/{id}', 'RoleController@edit')->name('role.edit');
      Route::post('', 'RoleController@store')->name('role.store');
      Route::post('update/{id}', 'RoleController@update')->name('role.update');
      Route::post('delete/{id}', 'RoleController@delete')->name('role.delete');    
    });
  
    Route::prefix('tiket')->group(function(){
      Route::get('', 'TiketWisataController@index')->name('tiket.index');
      Route::get('ax', 'TiketWisataController@axIndex')->name('tiket.axIndex');
      Route::get('tambah', 'TiketWisataController@add')->name('tiket.add');
      Route::get('detail/{id}', 'TiketWisataController@detail')->name('tiket.detail');
      Route::get('edit/{id}', 'TiketWisataController@edit')->name('tiket.edit');
      Route::post('', 'TiketWisataController@store')->name('tiket.store');
      Route::post('update/{id}', 'TiketWisataController@update')->name('tiket.update');
      Route::post('delete/{id}', 'TiketWisataController@delete')->name('tiket.delete');    
    });
  
    Route::prefix('target-perolehan')->group(function(){
      Route::get('', 'TargetPerolehanController@index')->name('target_perolehan.index');
      Route::post('', 'TargetPerolehanController@store')->name('target_perolehan.store');
      Route::post('update/{id}', 'TargetPerolehanController@update')->name('target_perolehan.update');
      Route::post('delete/{id}', 'TargetPerolehanController@delete')->name('target_perolehan.delete');    
    });
  
    Route::prefix('biaya-operasional')->group(function(){
      Route::get('', 'BiayaOperasionalController@index')->name('biaya_operasional.index');
      Route::post('', 'BiayaOperasionalController@store')->name('biaya_operasional.store');
      Route::post('update/{id}', 'BiayaOperasionalController@update')->name('biaya_operasional.update');
      Route::post('delete/{id}', 'BiayaOperasionalController@delete')->name('biaya_operasional.delete');    
    });
  
    Route::prefix('mitra')->group(function(){
      Route::get('', 'MitraController@index')->name('mitra.index');
      Route::get('ax', 'MitraController@axIndex')->name('mitra.axIndex');
      Route::post('', 'MitraController@store')->name('mitra.store');
      Route::post('update/{id}', 'MitraController@update')->name('mitra.update');
      Route::post('delete/{id}', 'MitraController@delete')->name('mitra.delete');    
    });
  });
});

app/TiketWisata.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class TiketWisata extends Model{

  public function bagiHasil(){
    return $this->hasMany('App\BagiHasil');
  }

  public function getCreatedAtAttribute($date){
    return Carbon::parse($date);
  }

  public function getJenisWaktuAttribute($jenis){
    return $jenis == 'all' ? 'SEMUA HARI' : strtoupper($jenis);
  }

  public function getHargaFormatAttribute(){
    return number_format($this->harga);
  }

  public function getActiveAttribute($date){
    return $this->is_active ? 'Aktif' : 'Dimatikan';
  }

  public function komponenHarga(){
    return $this->hasMany('App\KomponenHarga');
  }

  public function lokasi(){
    return $this->belongsTo('App\Lokasi');
  }

  public function loket(){
    return $this->belongsTo('App\Loket');
  }

  public function jenisTiket(){
    return $this->belongsTo('App\JenisTiket');
  }

  public function scopeActive($query){
    return $query->where('is_active', true);
  }

  public function scopeInMyOrganization($query){
    return $query->whereHas('lokasi', function($q){
      $q->whereIn('kph_id', Auth::user()->kph_list_id);
    });
  }

  public function transaksi(){
    return $this->hasMany('App\TransaksiTiket');
  }

}

app/Http/Controllers/LaporanController.php
<?php

namespace App\Http\Controllers;

use App\MyClass\Common;

use PDF;
use App\BiayaPengurang;
use App\PendapatanBagiHasi;
use App\Lokasi;
use App\Kph;
use App\PendapatanBagiHasil;
use App\TargetPerolehan;
use App\TiketWisata;
use App\TransaksiTiket;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class LaporanController extends Controller{
  
  public function perolehan(Request $request){
    Common::hasPermission();

    $bulan = null;
    $tahun = null;
    $laporan = false;
    $lokasi = Lokasi::active()->inMyOrganization()->get();
    $date = Carbon::parse("{$bulan}-01");
    $periode = $request->periode;

    if($request->bulan && $request->kph){
      $laporan = true;
      $bulan = date('Y-m', strtotime($request->bulan));
      $tahun = date('Y', strtotime($request->bulan));
      $lokasi = Lokasi::active()->whereKph($request->kph)->get();

      if(!$lokasi->count()){
        return redirect()->back()->with('danger', 'Belum Ada Transaksi');
      }
    }

    if($laporan && $request->laporan == 'pendapatan'){
      $targetPendapatan = TargetPerolehan::active()->kph($request->kph)->where('tahun', $tahun)->sum('pendapatan');

      $filename = 'pendapatan_'.$bulan.'.pdf';
      PDF::loadView('laporan.pendapatan_pdf', compact('lokasi', 'targetPendapatan', 'bulan', 'tahun', 'date', 'periode'))
      ->setPaper('legal', 'landscape')
      ->save("report/{$filename}");

      return response()->file("report/{$filename}");
    }

    if($laporan && $request->laporan == 'pengunjung'){
      $targetPengunjung = TargetPerolehan::active()->kph($request->kph)->where('tahun', $tahun);
      
      $filename = 'pengunjung_'.$bulan.'.pdf';
      PDF::loadView('laporan.pengunjung_pdf', compact('lokasi', 'bulan', 'tahun', 'targetPengunjung', 'date', 'periode'))
      ->setPaper('legal', 'landscape')
      ->save("report/{$filename}");
      
      return response()->file("report/{$filename}");
    }

    $kph = Kph::active()->inMyOrganization()->get();
    return view('laporan.pendapatan', compact('kph'));

  }

  public function beritaAcara(Request $request){
    Common::hasPermission();

    $tiketWisata = TiketWisata::find($request->id);
    $tiketByLokasi = TiketWisata::where('lokasi_id', $tiketWisata->lokasi_id)->get();

    $transaksi = TransaksiTiket::where('tiket_wisata_id', $tiketWisata->id)
    ->select(DB::raw('*, Date(created_at) as created_at, min(nomor_karcis) as min, max(nomor_karcis) as max, count(created_at) as total'))
    ->startDate($request->tanggal_dari)
    ->endDate($request->tanggal_sampai)
    ->groupBy(DB::raw('Date(created_at), tiket_wisata_id '))
    ->get();

    if(!count($transaksi)){
      return redirect()->back()->with('danger', 'Data Tidak Ditemukan');
    }

    $tanggal = [
      'dari' => Carbon::parse($request->tanggal_dari),
      'sampai' => Carbon::parse($request->tanggal_sampai),
    ];

    $biayaKomponen = BiayaPengurang::select(DB::raw('*, sum(total_biaya_operasional) as total'))
    ->where('lokasi_id', $tiketWisata->lokasi_id)
    ->groupBy('biaya_operasional_id')
    ->get();

    $bagiHasil = PendapatanBagiHasil::select(DB::raw('
      sum(bagi_hasil_mitra) as bagi_hasil_mitra, 
      sum(bagi_hasil_perhutani) as bagi_hasil_perhutani,
      sum(bagi_hasil_mitra) + sum(bagi_hasil_perhutani) as total'))
    ->where('lokasi_id', $tiketWisata->lokasi_id)
    ->first();

    $filename = 'berita_acara_'.$tiketWisata->lokasi->nama.'.pdf';
    PDF::loadView('laporan.berita_acara_pdf', compact('tiketWisata', 'transaksi', 'tiketByLokasi', 'tanggal', 'biayaKomponen', 'bagiHasil'))
    ->setPaper('a4', 'potrait')
    ->save("report/{$filename}");

    return response()->file("report/{$filename}");
  }

  public function realisasi(){
    Common::hasPermission();

    $targetPerolehan = TargetPerolehan::where('tahun', date('Y'))->get();
    return view('laporan.realisasi', compact('targetPerolehan'));
  }

}

resources/views/laporan/berita_acara_pdf.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <style>
  @page { 
    margin: 1.5cm;
  }
  
  body { 
    margin: 0.5px; 
    font-family: Arial, Helvetica, sans-serif;
  }
  
  table{
    width: 100%;
    border: 1px black solid;
    border-collapse: collapse;
    font-size: 12px;
  }  

  table th, table td{
    border: 1px black solid;
    padding: 2px 10px; 
  }
  
  h5{
    text-align: center;
    text-transform: uppercase;
  }

  h5, p{
    margin: 0;
    padding: 0;
    font-size: 12px;    
  }

  .tbody-header{
    background: #e2e2e2;
    text-align: center;
    font-weight: bold;
  }

  .text-right{
    text-align: right;
  }

  .text-left{
    text-align: left;
  }

  .text-center{
    text-align: center;
  }

  </style>
</head>
<body>
  
  <div style="margin-bottom:30px;">
    <h5>Berita Acara dan Lampiran Pendapatan</h5>
    <h5>{{ $tiketWisata->lokasi->nama }}</h5>
    <h5>Periode Tanggal {{ $tanggal['dari']->format('d-m-Y') }} s.d {{ $tanggal['sampai']->format('d-m-Y') }}</h5>
  </div>

  <div class="" style="margin-bottom:10px;">
    <p>Yang bertanda tangan di bawah ini: </p>
    <p style="margin-left:20px; margin-top:10px;">Nama : ...............</p>
    <p style="margin-left:20px; margin-bottom:10px;">Jabatan : .............</p>
    <p>Menyerahkan Bagi Hasil Pendapatan kepada Perum Perhutani</p>
    <p><strong>Periode Tanggal {{ $tanggal['dari']->format('d-m-Y') }} s.d {{ $tanggal['sampai']->format('d-m-Y') }}</strong></p>
  </div>

  @php $i=0; @endphp
  @foreach ($tiketByLokasi as $tiket)    
    <table align="center" style="margin-top:30px; {{ $i != 0 ? 'page-break-before: always;' : null }} ">
      <thead>
        <tr>
          <th rowspan="2" style="width:20px;">No</th>
          <th rowspan="2">Tanggal</th>
          <th colspan="4" class="text-center">{{ $tiket->jenisTiket->nama }} <br> {{ $tiket->harga }} - {{ $tiket->jenis_waktu }}</th>
        </tr>
        <tr>
          <th colspan="2">Nomor Karcis</th>
          <th>Jumlah Lembar</th>
          <th>Rp</th>
        </tr>
      </thead>
      <tbody>
        <tr class="tbody-header">
          <td>1</td>
          <td>2</td>
          <td colspan="2">3</td>
          <td>4</td>
          <td>5</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        @php 
          $no=1; 
          $jmhLembar=0; 
          $jmhPendapatan=0; 
          $jmhBagiPerhutani=0; 
          $jmhBagiMitra=0;
          $transaksi = $tiket->transaksi()
          ->startDate($tanggal['dari']->format('Y-m-d'))
          ->endDate($tanggal['sampai']->format('Y-m-d'))
          ->byDate()
          ->transaksi()
          ->get();
        @endphp

        @foreach($transaksi as $o)
        <tr>
          <td class="text-center">{{ $no++ }}</td>
          <td class="text-center">{{ $o->created_at->format('d-m-Y') }}</td>
          <td class="text-center">{{ $o->min }}</td>
          <td class="text-center">{{ $o->max }}</td>
          <td class="text-right">{{ number_format($o->total) }}</td>
          <td class="text-right">{{ number_format($tiket->harga * $o->total) }}</td>
          @php
            $pendapatan = $tiket->harga * $o->total;
            $jmhLembar += $o->total; $jmhPendapatan += $pendapatan; 
          @endphp
        </tr>
        @endforeach
        <tr class="tbody-header">
          <td></td>
          <td class="text-center">TOTAL</td>
          <td></td>
          <td></td>
          <td class="text-right">{{ number_format($jmhLembar) }}</td>
          <td class="text-right">{{ number_format($jmhPendapatan) }}</td>
        </tr>
      </tbody>
    </table>
    
    <div style="margin:20px 0 10px 0">
      <h5 class="">Rekapitalusai Pendapatan para Pihak</h5>
    </div>

    <table align="center" style="margin-top:30px">
      <thead>
        <tr>
          <th rowspan="2" style="width:20px;">No</th>
          <th rowspan="2">Komponen</th>
          <th rowspan="2">Total</th>
          <th colspan="2" class="text-center">Perhutani</th>
          <th colspan="2" class="text-center">LMDH</th>
        </tr>
        <tr>
          <th>Rp</th>
          <th>Jumlah</th>
          <th>Rp</th>
          <th>Jumlah</th>
        </tr>
      </thead>
      <tbody>
        @php $no=1; $total=0; @endphp
        @foreach($tiket->komponenHarga as $o)
        <tr>
          <td class="text-center">{{ $no++ }}</td>
          <td>{{ $o->biayaOperasional->nama }}</td>
          <td class="text-right">{{ number_format($jmhLembar) }}</td>
          <td class="text-right">{{ number_format($o->biaya) }}</td>
          <td class="text-right">{{ number_format($jmhLembar * $o->biaya) }}</td>
          <td class="text-right">-</td>
          <td class="text-right">-</td>
          @php 
            $total = $jmhLembar * $o->biaya;
            $jmhBagiPerhutani += $total 
          @endphp
        </tr>
        @endforeach

        @php $totalPerhutani=0; $totalMitra=0; @endphp
        @foreach($tiket->bagiHasil as $o)
        <tr>
          <td class="text-center">{{ $no++ }}</td>
          <td>Bagi Hasil {{ $o->mitra->nama }}</td>
          <td class="text-right">{{ $jmhLembar }}</td>
          <td class="text-right">{{ number_format($o->bagi_perhutani) }}</td>
          <td class="text-right">{{ number_format($jmhLembar * $o->bagi_perhutani) }}</td>
          <td class="text-right">{{ number_format($o->bagi_mitra)  }}</td>
          <td class="text-right">{{ number_format($jmhLembar * $o->bagi_mitra) }}</td>
          @php 
            $totalPerhutani = $jmhLembar * $o->bagi_perhutani;
            $totalMitra = $jmhLembar * $o->bagi_mitra;
            $jmhBagiPerhutani += $totalPerhutani; 
            $jmhBagiMitra += $totalMitra 
          @endphp
        </tr>
        @endforeach
        <tr class="tbody-header">
          <td></td>
          <td>TOTAL</td>
          <td></td>
          <td></td>
          <td class="text-right">{{ number_format($jmhBagiPerhutani) }}</td>
          <td></td>
          <td class="text-right">{{ number_format($jmhBagiMitra) }}</td>
        </tr>
      </tbody>
    </table>
  @php $i++; @endphp
  @endforeach

  <div style="margin:20px 0 10px 0">
    <h5 class="">Total Rekapitalusai Pendapatan</h5>
  </div>

  <table align="center" style="margin-top:30px">
    <thead>
      <tr>
        <th style="width:20px;">No</th>
        <th>Komponen</th>
        <th>Total</th>
      </tr>
    </thead>
    <tbody>
      @php $no=1; @endphp
      @foreach($biayaKomponen as $o)
      <tr>
        <td>{{ $no++ }}</td>
        <td>{{ $o->kebutuhan }}</td>
        <td class="text-right">{{ number_format($o->total) }}</td>
      </tr>
      @endforeach
      <tr>
        <td>{{ $no++ }}</td>
        <td>Bagi Hasil Mitra</td>
        <td class="text-right">{{ number_format($bagiHasil->bagi_hasil_mitra) }}</td>
      </tr>
      <tr>
        <td>{{ $no++ }}</td>
        <td>Bagi Hasil Perhutani</td>
        <td class="text-right">{{ number_format($bagiHasil->bagi_hasil_perhutani) }}</td>
      </tr>
    </tbody>
  </table>

  <div class="" style="margin-top:10px; margin-bottom:50px;">
    <div style="width:50%; float:left">
      <p>Yang Menerima</p>
      <p>Junior Manager Bisnis</p>
      <p style="margin-top:50px;"><strong>( ...................... )</strong></p>
    </div>
    <div style="width:50%; float:right">
      <p>Yang Menyerahkan</p>
      <p>Ketua ......</p>
      <p style="margin-top:50px;"><strong>( ...................... )</strong></p>
    </div>
  </div>

  <span style="margin-top:50px; color:grey; font-size:10px">di-download pada: {{ date('d F Y H:i:s') }}</span>
</body>
</html>

resources/views/laporan/pendapatan.blade.php
@extends('app')

@section('title')
Laporan Perolehan
@endsection

@section('content')
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="card-box">
      <h4 class="header-title m-t-0">Laporan Perolehan</h4>
      <form action="">
        <div class="row">
            <div class="col-sm-12 m-b-10">
              <select name="laporan" class="form-control select2" required>
                <option value="">Pilih Jenis Laporan</option>
                <option value="pendapatan">Pendapatan</option>
                <option value="pengunjung">Pengunjung</option>
              </select>
            </div>
            <div class="col-sm-12 m-b-10">
              <select name="kph" class="form-control select2" required>
                <option value="">Pilih Kph</option>
                @foreach($kph as $o)
                <option value="{{ $o->id }}">{{ $o->nama }}</option>
                @endforeach
              </select>
            </div>
            <div class="col-sm-12 m-b-10">
              <select name="periode" class="form-control" required>
                <option value="">Pilih Periode</option>
                <option value="1">Periode I</option>
                <option value="2">Periode II</option>
              </select>
            </div>
            <div class="col-sm-12 m-b-10">
              <input type="text" name="bulan" class="form-control" placeholder="Bulan" id="datepicker" required>
            </div>
            <div class="col-sm-2">
              <button class="btn btn-primary">Lihat Laporan</button>
            </div>
        </div>
      </form>
    </div>
  </div>
</div>
@endsection

@section('css-top')
<!-- DataTables -->
<link href="{{ asset('template/assets/plugins/datatables/jquery.dataTables.min.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('template/assets/plugins/datatables/buttons.bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('template/assets/plugins/datatables/fixedHeader.bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('template/assets/plugins/datatables/responsive.bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('template/assets/plugins/datatables/scroller.bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
<!-- Datatable init js -->
<script src="{{ asset('template/assets/pages/datatables.init.js') }}"></script>
<!-- datepicker -->
<link href="{{ asset('template/assets/plugins/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}" rel="stylesheet">
<link href="{{ asset('template/assets/plugins/bootstrap-daterangepicker/daterangepicker.css') }}" rel="stylesheet">
<!-- select2 -->
<link href="{{ asset('template/assets/plugins/select2/dist/css/select2.css') }}" rel="stylesheet" type="text/css">
<link href="{{ asset('template/assets/plugins/select2/dist/css/select2-bootstrap.css') }}" rel="stylesheet" type="text/css">
@endsection

@section('js-top')
  <!-- Datatables-->
  <script src="{{ asset('template/assets/plugins/datatables/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('template/assets/plugins/datatables/dataTables.bootstrap.js') }}"></script>
  <script src="{{ asset('template/assets/plugins/datatables/dataTables.buttons.min.js') }}"></script>
  <script src="{{ asset('template/assets/plugins/datatables/buttons.bootstrap.min.js') }}"></script>
  <script src="{{ asset('template/assets/plugins/datatables/jszip.min.js') }}"></script>
  <script src="{{ asset('template/assets/plugins/datatables/pdfmake.min.js') }}"></script>
  <script src="{{ asset('template/assets/plugins/datatables/vfs_fonts.js') }}"></script>
  <script src="{{ asset('template/assets/plugins/datatables/buttons.html5.min.js') }}"></script>
  <script src="{{ asset('template/assets/plugins/datatables/buttons.print.min.js') }}"></script>
  <script src="{{ asset('template/assets/plugins/datatables/dataTables.fixedHeader.min.js') }}"></script>
  <script src="{{ asset('template/assets/plugins/datatables/dataTables.keyTable.min.js') }}"></script>
  <script src="{{ asset('template/assets/plugins/datatables/dataTables.responsive.min.js') }}"></script>
  <script src="{{ asset('template/assets/plugins/datatables/responsive.bootstrap.min.js') }}"></script>
  <script src="{{ asset('template/assets/plugins/datatables/dataTables.scroller.min.js') }}"></script>
  <!-- Datatable init js -->
  <script src="{{ asset('template/assets/pages/datatables.init.js') }}"></script>
  <!-- Datepicker -->
  <script src="{{ asset('template/assets/plugins/moment/moment.js') }}"></script>
  <script src="{{ asset('template/assets/plugins/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}"></script>
  <script src="{{ asset('template/assets/plugins/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
  <!-- select2 -->
  <script src="{{ asset('template/assets/plugins/select2/dist/js/select2.min.js') }}"></script>
@endsection

@section('js-bottom')
<script type="text/javascript">
  $(document).ready(function () {
    $('.select2').select2();
    $('#datepicker').datepicker({
      orientation: 'top',
      format: "yyyy-mm",
      viewMode: "months", 
      minViewMode: "months",
    });
    TableManageButtons.init()
  });
</script>
@endsection